spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/northwind
#spring.datasource.url=jdbc:postgresql://172.18.0.2:5432/northwind
spring.datasource.username=northwind
spring.datasource.password=northwind
#logging.structured.format.console=ecs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
